### ISSUE TITLE
SensorBar "isOneSensed()" method

### ISSUE THREAD

**Issue by AshwinS27** [The-Charge/Resistance2019#12]
I was just checking out the code and found out the the "isOneSensed()" method in SensorBar uses the following logic...
for(int x = 0; x < 5; x++){
            if(sensBar[x].get() == true){
                seesLine = true;
                x = 5;
            }
        }
BUT... sensors 0 and 4 use inverted logic (seeing line == false)..so you guys have to fix that

**Comment by Shalmezad** [comment]
I would *strongly* recommend:

- [ ] Making a method in SensorBar called `isSensorTriggered(int idx)`. Have it return true if the given index sees white (`.get()` if 1,2,3. `!.get()` if 0,4)
- [ ] Change the logic in `isOneSensed()` to use `isSensorTriggered` instead of calling the sensors themselves.
- [ ] Change the logic in `PIDLineFollow()` to use `SensorBar.isSensorTriggered` instead of calling the sensors themselves.

Doing some more digging, there's other things that should probably be refactored:
- [ ] Move instances of `5` to SensorBar as a constant (like `NUM_LINE_SENSORS`)
- [ ] Stop abbreviating variable names like `doe` and `ctr` (you're using an IDE, Ctrl+Space is your friend). 
- [ ] Get rid of `sensArray` in PIDLineFollow
